apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: backend-app
  name: backend-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: backend-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend-app
    spec:
      containers:
      - image: regBackend.azurecr.io/cardozoqsantiago/adnsantiagocardozoq:v1
        name: app
        imagePullPolicy: Always
        resources: {}
        ports:
          - containerPort: 8080 
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: backend-app
  labels:
    run: backend-app
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: backend-app
  type: LoadBalancer