jasypt:
   encryptor:
      password: ${jasyptpwd:secretkey}
      algorithm: PBEWithMD5AndDES

server:
   port: 8080
   servlet:
      context-path: /AdnSantiagoCardozoQ
      session:
         timeout: 21600s

spring:
   datasource:
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:mysql://localhost:3306/adn?autoReconnect=true&useSSL=false
      username: root
      password: 12345
      hikari:
         poolName: pool
