CREATE TABLE producto (
  id INT NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(100) NOT NULL,
  tipo_producto VARCHAR(45) NOT NULL,
  cantidad INT NOT NULL,
  precio DECIMAL(2) NOT NULL,
  PRIMARY KEY (id));